version: '3'
services:
  nginx-front:
    image: nginx:1.17.8
    volumes:
      - ./front-end:/code
    networks:
      net:
        ipv4_address: 192.168.240.2
  nginx-back:
    image: nginx:1.17.8
    volumes:
      - ./back-end:/code
    networks:
      net:
        ipv4_address: 192.168.240.3
  python-back:
    image: python:latest
    volumes:
      - ./back-end:/code
    networks:
      net:
        ipv4_address: 192.168.240.4
networks:
  net:
    driver: bridge
    ipam:
      config: 192.168.240.0/24